#!/usr/bin/env python3
"""End-to-end concurrency boundary probe for the skill-poison-scan service.

It drives the public HMI or M2M upload endpoint with several concurrent scans,
polls tasks to completion, and samples both:

* server queue depth:  GET  /actuator/prometheus  -> skillscan_queue_depth
* engine active scans: GET  <engine>/health        -> active_scans / max_concurrent_scans

The pass/fail decision is deliberately strict: it fails when the *observed*
engine active-scan count exceeds the configured boundary, when tasks are stuck
or rejected, or when the measured plateau does not match the expected boundary.

No third-party packages are required (Python 3.9+ standard library only).
"""

from __future__ import annotations

import argparse
import io
from collections import Counter
import json
import sys
import threading
import time
import urllib.error
import urllib.request
import uuid
import zipfile
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from typing import Any

TERMINAL_STATES = {"SUCCEEDED", "FAILED", "CANCELED"}
HTTP_ACCEPTED = {200, 202}


class ProbeError(RuntimeError):
    pass


@dataclass
class EngineSample:
    ts: float
    active_scans: int
    queue_depth: int | None
    max_concurrent_scans: int | None
    engine_status: str | None = None


@dataclass
class TaskResult:
    task_id: str
    submit_elapsed: float
    submit_status: int | None
    submit_error: str | None
    end_to_end: float | None = None
    terminal_status: str | None = None
    error_code: str | None = None
    error_msg: str | None = None


@dataclass
class LevelResult:
    level: int
    total: int
    accepted: int
    terminal: int
    succeeded: int
    failed: int
    stuck: int
    http_errors: int
    submit_p50_ms: float
    submit_p95_ms: float
    submit_max_ms: float
    e2e_p50_ms: float | None
    e2e_p95_ms: float | None
    e2e_max_ms: float | None
    observed_max_active: int
    max_queue_depth: int
    engine_limit: int | None
    expected_limit: int
    checks: list[str] = field(default_factory=list)


def parse_levels(raw: str) -> list[int]:
    tokens = [t for t in raw.replace(",", " ").split() if t]
    levels: list[int] = []
    for token in tokens:
        try:
            value = int(token)
        except ValueError as exc:
            raise argparse.ArgumentTypeError(f"invalid level {token!r}") from exc
        if value <= 0:
            raise argparse.ArgumentTypeError("levels must be positive")
        levels.append(value)
    return levels or [2, 8, 16, 32, 64]


def build_opener() -> urllib.request.OpenerDirector:
    # Localhost probe should not accidentally use a proxy configured in the shell.
    return urllib.request.build_opener(urllib.request.ProxyHandler({}))


OPENER = build_opener()


def request_json(
    url: str,
    *,
    method: str = "GET",
    data: bytes | None = None,
    headers: dict[str, str] | None = None,
    timeout: float = 30.0,
) -> tuple[int | None, Any, bytes]:
    req = urllib.request.Request(url, data=data, headers=headers or {}, method=method)
    try:
        with OPENER.open(req, timeout=timeout) as resp:
            raw = resp.read()
            status = resp.status
            parsed = _safe_json(raw)
            return status, parsed, raw
    except urllib.error.HTTPError as exc:
        raw = exc.read()
        return exc.code, _safe_json(raw), raw
    except Exception as exc:  # network error, timeout, DNS, connection refused
        return None, {"_error": str(exc)}, b""


def _safe_json(raw: bytes) -> Any:
    if not raw:
        return None
    try:
        return json.loads(raw.decode("utf-8"))
    except Exception:
        return {"_raw": raw[:200].decode("utf-8", errors="replace")}


def make_skill_zip(label: str, file_count: int = 40) -> bytes:
    """Create a deterministic, valid skill zip in memory.

    A modest number of files is included on purpose: tiny one-file fixtures can
    finish faster than the sampling interval, which would make the engine
    `active_scans` plateau impossible to observe reliably.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(
            "SKILL.md",
            f"---\nname: probe-{label}\ndescription: concurrency probe {label}\n---\n"
            f"# Probe {label}\n\nThis skill is generated by scripts/concurrency_probe.py.\n",
        )
        zf.writestr(
            "tool.py",
            "def run(query: str) -> str:\n    return query.strip()\n",
        )
        for index in range(file_count):
            zf.writestr(
                f"src/module_{index:03d}.py",
                f"# generated module {index}\ndef helper_{index}(value: int) -> int:\n    return value + {index}\n",
            )
            zf.writestr(f"resources/notes_{index:03d}.md", f"fixture note {index}\n")
    return buf.getvalue()


def build_multipart(
    file_bytes: bytes,
    filename: str,
    fields: dict[str, str],
    file_field: str = "file",
) -> tuple[bytes, str]:
    boundary = "----skillscan-probe-" + uuid.uuid4().hex
    body = io.BytesIO()
    for name, value in fields.items():
        body.write(
            f"--{boundary}\r\n"
            f'Content-Disposition: form-data; name="{name}"\r\n\r\n'
            f"{value}\r\n".encode("utf-8")
        )
    body.write(
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="{file_field}"; filename="{filename}"\r\n'
        f"Content-Type: application/zip\r\n\r\n".encode("utf-8")
    )
    body.write(file_bytes)
    body.write(f"\r\n--{boundary}--\r\n".encode("utf-8"))
    return body.getvalue(), boundary


def submit_scan(
    base_url: str,
    m2m: bool,
    zip_bytes: bytes,
    use_llm: bool,
    timeout: float,
) -> TaskResult:
    group = "m2m" if m2m else "v1"
    endpoint = f"{base_url.rstrip('/')}/api/{group}/v1/scans" if m2m else f"{base_url.rstrip('/')}/api/v1/scans"
    fields = {"useLlm": "true" if use_llm else "false"}
    if m2m:
        fields["metadata"] = json.dumps({"repo": "concurrency-probe", "source": "scripts/concurrency_probe.py"})
    body, boundary = build_multipart(zip_bytes, "probe.zip", fields)
    headers = {"Content-Type": f"multipart/form-data; boundary={boundary}"}

    started = time.perf_counter()
    status, parsed, _ = request_json(endpoint, method="POST", data=body, headers=headers, timeout=timeout)
    elapsed = time.perf_counter() - started

    task_id = None
    error = None
    if status in HTTP_ACCEPTED and isinstance(parsed, dict):
        data = parsed.get("data") or {}
        task_id = data.get("taskId")
    elif status is None:
        error = str((parsed or {}).get("_error", "network error"))
    else:
        error = f"HTTP {status}: {json.dumps(parsed, ensure_ascii=False)[:300]}"

    return TaskResult(task_id=task_id or "", submit_elapsed=elapsed, submit_status=status, submit_error=error)


def get_task(base_url: str, m2m: bool, task_id: str, timeout: float = 10.0) -> dict[str, Any] | None:
    group = "m2m" if m2m else "v1"
    endpoint = f"{base_url.rstrip('/')}/api/{group}/v1/scans/{task_id}" if m2m else f"{base_url.rstrip('/')}/api/v1/scans/{task_id}"
    _, parsed, _ = request_json(endpoint, method="GET", timeout=timeout)
    if isinstance(parsed, dict):
        return parsed.get("data")
    return None


class EngineSampler:
    """Periodically samples engine /health and server queue depth while scans run."""

    def __init__(self, engine_url: str, server_url: str, interval: float):
        self.engine_url = engine_url.rstrip("/")
        self.server_url = server_url.rstrip("/")
        self.interval = interval
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None
        self._lock = threading.Lock()
        self.samples: list[EngineSample] = []
        self.max_active = 0
        self.max_queue_depth = 0
        self.engine_limit: int | None = None

    def start(self) -> None:
        self._thread = threading.Thread(target=self._run, name="engine-sampler", daemon=True)
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=5)

    def _run(self) -> None:
        while not self._stop.is_set():
            sample = self._sample()
            with self._lock:
                self.samples.append(sample)
                self.max_active = max(self.max_active, sample.active_scans)
                if sample.queue_depth is not None:
                    self.max_queue_depth = max(self.max_queue_depth, sample.queue_depth)
                if sample.max_concurrent_scans is not None:
                    self.engine_limit = sample.max_concurrent_scans
            self._stop.wait(self.interval)

    def _sample(self) -> EngineSample:
        ts = time.time()
        _, health, _ = request_json(f"{self.engine_url}/health", timeout=5)
        active = 0
        limit = None
        status = None
        if isinstance(health, dict):
            active = int(health.get("active_scans") or 0)
            limit = health.get("max_concurrent_scans")
            if limit is not None:
                limit = int(limit)
            status = health.get("status")

        queue_depth: int | None = None
        _, _, metrics_raw = request_json(f"{self.server_url}/actuator/prometheus", timeout=5)
        queue_depth = parse_prometheus_gauge(metrics_raw, "skillscan_queue_depth")

        return EngineSample(ts=ts, active_scans=active, queue_depth=queue_depth, max_concurrent_scans=limit, engine_status=status)


def list_tasks(base_url: str, size: int) -> list[dict[str, Any]]:
    """Fetch the newest tasks in one request, avoiding a per-task GET storm.

    HMI list is intentionally used even for M2M submissions: both controllers
    persist into the same scan_task table, so the list contains both groups.
    """
    endpoint = f"{base_url.rstrip('/')}/api/v1/scans?page=1&size={size}"
    _, parsed, _ = request_json(endpoint, timeout=10)
    if not isinstance(parsed, dict):
        return []
    data = parsed.get("data") or {}
    items = data.get("items") if isinstance(data, dict) else None
    return items if isinstance(items, list) else []


def wait_for_terminal(
    base_url: str,
    m2m: bool,
    tasks: list[TaskResult],
    timeout: float,
    poll_interval: float,
) -> tuple[list[TaskResult], list[TaskResult]]:
    """Poll tasks until terminal or timeout. Returns (finished, stuck)."""
    deadline = time.time() + timeout
    pending = {t.task_id: t for t in tasks if t.task_id}
    finished: list[TaskResult] = []

    while pending and time.time() < deadline:
        # Fetch a page large enough to include every task from this level.
        items = list_tasks(base_url, size=max(50, len(pending) + 10))
        seen: set[str] = set()
        for item in items:
            task_id = item.get("taskId")
            if not task_id or task_id not in pending:
                continue
            seen.add(task_id)
            task = pending[task_id]
            task.terminal_status = item.get("status")
            task.error_code = item.get("errorCode")
            task.error_msg = item.get("errorMsg")
            task.end_to_end = time.time() - _task_created_ts.get(task_id, time.time())
            if task.terminal_status in TERMINAL_STATES:
                pending.pop(task_id, None)
                finished.append(task)

        # Fallback for tasks that somehow did not appear in the first page.
        missing = [task_id for task_id in pending if task_id not in seen]
        if missing:
            for task_id in missing[:5]:
                task_dto = get_task(base_url, m2m, task_id)
                task = pending[task_id]
                if isinstance(task_dto, dict):
                    task.terminal_status = task_dto.get("status")
                    task.error_code = task_dto.get("errorCode")
                    task.error_msg = task_dto.get("errorMsg")
                    task.end_to_end = time.time() - _task_created_ts.get(task_id, time.time())
                    if task.terminal_status in TERMINAL_STATES:
                        pending.pop(task_id, None)
                        finished.append(task)

        if pending:
            time.sleep(poll_interval)

    return finished, list(pending.values())


# taskNo -> monotonic-ish creation time captured just before submit.
_task_created_ts: dict[str, float] = {}


def run_level(
    *,
    level: int,
    base_url: str,
    m2m: bool,
    engine_url: str,
    use_llm: bool,
    timeout: float,
    poll_interval: float,
    sample_interval: float,
    expected_limit: int,
    fixture_files: int,
    seed_prefix: str,
) -> LevelResult:
    # Build unique zips per task so SkillSpector cannot accidentally reuse any cached state.
    zips = [make_skill_zip(f"{seed_prefix}-{level}-{i}", fixture_files) for i in range(level)]

    sampler = EngineSampler(engine_url, base_url, sample_interval)
    sampler.start()

    tasks: list[TaskResult] = []
    started_at = time.perf_counter()
    # Submission is intentionally as parallel as requested: `level` simultaneous uploads.
    with ThreadPoolExecutor(max_workers=level) as executor:
        futures = []
        for i, zip_bytes in enumerate(zips):
            created = time.time()
            fut = executor.submit(submit_scan, base_url, m2m, zip_bytes, use_llm, timeout)
            # We don't have the taskId until submit returns; keep an index->created map below.
            futures.append((i, created, fut))
        for i, created, fut in futures:
            result = fut.result()
            if result.task_id:
                _task_created_ts[result.task_id] = created
            tasks.append(result)
    submit_wall = time.perf_counter() - started_at

    accepted_tasks = [t for t in tasks if t.task_id and t.submit_status in HTTP_ACCEPTED]
    http_errors = [t for t in tasks if not t.task_id or t.submit_status not in HTTP_ACCEPTED]

    finished, stuck = wait_for_terminal(base_url, m2m, accepted_tasks, timeout, poll_interval)
    sampler.stop()

    succeeded = [t for t in finished if t.terminal_status == "SUCCEEDED"]
    failed = [t for t in finished if t.terminal_status in ("FAILED", "CANCELED")]

    submit_ms = sorted(t.submit_elapsed * 1000 for t in tasks)
    e2e_values = sorted((t.end_to_end or 0) * 1000 for t in finished if t.end_to_end is not None)

    observed_max_active = sampler.max_active
    engine_limit = sampler.engine_limit
    expected = expected_limit
    if engine_limit is not None:
        expected = min(expected, engine_limit)
    if expected is None or expected <= 0:
        expected = observed_max_active

    checks: list[str] = []
    if observed_max_active > expected:
        checks.append(f"FAIL: observed active scans {observed_max_active} exceeded expected {expected}")
    else:
        checks.append(f"PASS: observed max active {observed_max_active} <= expected {expected}")
    if level > expected and observed_max_active < expected:
        checks.append(f"WARN: saturation plateau {observed_max_active} below expected {expected}; bottleneck is elsewhere")
    if http_errors:
        codes = Counter(str(t.submit_error) for t in http_errors)
        checks.append(f"FAIL: {len(http_errors)} submissions not accepted ({dict(codes)})")
    else:
        checks.append(f"PASS: all {level} uploads accepted with 202")
    if stuck:
        checks.append(f"FAIL: {len(stuck)} tasks stuck non-terminal after {timeout}s")
    else:
        checks.append(f"PASS: all accepted tasks reached a terminal state")
    if failed:
        checks.append(f"WARN: {len(failed)} tasks ended FAILED/CANCELED (first: {failed[0].terminal_status}/{failed[0].error_code})")

    return LevelResult(
        level=level,
        total=level,
        accepted=len(accepted_tasks),
        terminal=len(finished),
        succeeded=len(succeeded),
        failed=len(failed),
        stuck=len(stuck),
        http_errors=len(http_errors),
        submit_p50_ms=percentile(submit_ms, 50) if submit_ms else 0.0,
        submit_p95_ms=percentile(submit_ms, 95) if submit_ms else 0.0,
        submit_max_ms=max(submit_ms) if submit_ms else 0.0,
        e2e_p50_ms=percentile(e2e_values, 50) if e2e_values else None,
        e2e_p95_ms=percentile(e2e_values, 95) if e2e_values else None,
        e2e_max_ms=max(e2e_values) if e2e_values else None,
        observed_max_active=observed_max_active,
        max_queue_depth=sampler.max_queue_depth,
        engine_limit=engine_limit,
        expected_limit=expected,
        checks=checks,
    )


def parse_prometheus_gauge(raw: bytes, metric_name: str) -> int | None:
    """Parse a simple Prometheus text metric such as `skillscan_queue_depth 3.0`."""
    if not raw:
        return None
    text = raw.decode("utf-8", errors="replace")
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("#"):
            continue
        if line.startswith(metric_name):
            parts = line.split()
            if len(parts) >= 2:
                try:
                    return int(float(parts[1]))
                except ValueError:
                    return None
    return None


def percentile(values: list[float], pct: float) -> float:
    if not values:
        return 0.0
    if len(values) == 1:
        return values[0]
    k = (len(values) - 1) * (pct / 100.0)
    lo = int(k)
    hi = min(lo + 1, len(values) - 1)
    frac = k - lo
    return values[lo] * (1 - frac) + values[hi] * frac



def print_summary(results: list[LevelResult]) -> None:
    print("\nConcurrency boundary report")
    print("=" * 92)
    header = (
        f"{'level':>6} {'accept':>7} {'term':>6} {'ok':>5} {'fail':>5} {'stuck':>6} "
        f"{'sub_p95':>9} {'e2e_p95':>9} {'active':>7} {'queue':>6} {'limit':>6}"
    )
    print(header)
    print("-" * 92)
    for r in results:
        e2e = f"{r.e2e_p95_ms:8.0f}ms" if r.e2e_p95_ms is not None else "     n/a"
        print(
            f"{r.level:>6} {r.accepted:>7} {r.terminal:>6} {r.succeeded:>5} {r.failed:>5} {r.stuck:>6} "
            f"{r.submit_p95_ms:>8.0f}ms {e2e:>9} {r.observed_max_active:>7} {r.max_queue_depth:>6} {r.expected_limit:>6}"
        )
    print("=" * 92)
    all_pass = True
    for r in results:
        for check in r.checks:
            print(f"[level={r.level}] {check}")
            if check.startswith("FAIL"):
                all_pass = False
    print("=" * 92)
    print("RESULT:", "PASS" if all_pass else "FAIL")


def main() -> int:
    parser = argparse.ArgumentParser(description="Probe skill-scan service concurrency boundary.")
    parser.add_argument("--base-url", default="http://localhost:8080", help="SkillDetectServer base URL")
    parser.add_argument("--engine-url", default="http://localhost:8000", help="skillspector-engine base URL")
    parser.add_argument("--levels", default="2,8,16,32,64", help="comma/space separated concurrency levels")
    parser.add_argument("--m2m", action="store_true", help="use /api/m2m/v1 instead of HMI /api/v1")
    parser.add_argument("--use-llm", action="store_true", help="request LLM semantic pass (requires gateway config)")
    parser.add_argument("--server-max-active", type=int, default=8, help="expected server SCAN_CONCURRENCY_MAX_ACTIVE")
    parser.add_argument("--timeout", type=float, default=300.0, help="max seconds to wait for a level to drain")
    parser.add_argument("--poll-interval", type=float, default=1.0, help="task polling interval (seconds; lower values may hit HMI rate limit)")
    parser.add_argument("--sample-interval", type=float, default=0.2, help="engine sampling interval (seconds; lower is more precise but adds load)")
    parser.add_argument("--fixture-files", type=int, default=40, help="generated files per probe zip (increase if static scans finish too fast)")
    parser.add_argument("--json-output", help="write full results as JSON to this path")
    args = parser.parse_args()

    levels = parse_levels(args.levels)
    expected_limit = args.server_max_active

    if max(levels) > (60 if args.m2m else 120):
        print(f"WARNING: max level {max(levels)} exceeds the default "
              f"{'M2M 60/min' if args.m2m else 'HMI 120/min'} rate limit; "
              "run with RATE_LIMIT_ENABLED=false for a pure concurrency test.", file=sys.stderr)

    print("Preflight checks")
    print("=" * 92)
    for name, url in (("server readyz", f"{args.base_url.rstrip('/')}/readyz"), ("engine health", f"{args.engine_url.rstrip('/')}/health")):
        status, parsed, _ = request_json(url, timeout=10)
        ok = status == 200 and isinstance(parsed, (dict,)) and str(parsed.get("status", "")).upper() in {"UP", "OK"}
        print(f"  {name:>14}: HTTP {status} {'UP' if ok else json.dumps(parsed, ensure_ascii=False)}")
        if not ok:
            print("Preflight failed. Start services with `docker compose up -d` and re-run.", file=sys.stderr)
            return 2

    results: list[LevelResult] = []
    seed = uuid.uuid4().hex[:8]
    for level in levels:
        print(f"\nRunning level={level} (concurrent uploads) ...")
        result = run_level(
            level=level,
            base_url=args.base_url,
            m2m=args.m2m,
            engine_url=args.engine_url,
            use_llm=args.use_llm,
            timeout=args.timeout,
            poll_interval=args.poll_interval,
            sample_interval=args.sample_interval,
            expected_limit=expected_limit,
            fixture_files=args.fixture_files,
            seed_prefix=seed,
        )
        results.append(result)
        print(
            f"  accepted={result.accepted}/{result.total} terminal={result.terminal} ok={result.succeeded} "
            f"fail={result.failed} stuck={result.stuck} active_max={result.observed_max_active} "
            f"expected={result.expected_limit}"
        )

    print_summary(results)

    if args.json_output:
        payload = {
            "generated_at": time.time(),
            "base_url": args.base_url,
            "engine_url": args.engine_url,
            "m2m": args.m2m,
            "use_llm": args.use_llm,
            "levels": [asdict_public(r) for r in results],
        }
        with open(args.json_output, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2, ensure_ascii=False)
        print(f"\nWrote JSON report to {args.json_output}")

    return 0


def asdict_public(result: LevelResult) -> dict[str, Any]:
    return {
        "level": result.level,
        "total": result.total,
        "accepted": result.accepted,
        "terminal": result.terminal,
        "succeeded": result.succeeded,
        "failed": result.failed,
        "stuck": result.stuck,
        "http_errors": result.http_errors,
        "submit_p50_ms": result.submit_p50_ms,
        "submit_p95_ms": result.submit_p95_ms,
        "submit_max_ms": result.submit_max_ms,
        "e2e_p50_ms": result.e2e_p50_ms,
        "e2e_p95_ms": result.e2e_p95_ms,
        "e2e_max_ms": result.e2e_max_ms,
        "observed_max_active": result.observed_max_active,
        "max_queue_depth": result.max_queue_depth,
        "engine_limit": result.engine_limit,
        "expected_limit": result.expected_limit,
        "checks": result.checks,
    }


if __name__ == "__main__":
    raise SystemExit(main())
